### PR TITLE
Fix broken link to Meteor Blog

### PR DESCRIPTION
**Pull request by canac**

### CODE REVIEW

**Comment by ShMcK** [comment]
Good catch!

@Urigo this looks good :)

**Comment by Urigo** [comment]
I will add the `s` :)

**Comment by Tallyb** [comment]
Does that mean previous articles are gone? ;)

**Comment by canac** [comment]
@ShMcK and @Urigo, I tried HTTPS first but got a privacy error in Chrome because the certificate belongs to a248.e.akamai.net, so I went with HTTP instead.

**Pull request merged**
