### PR TITLE
Adding failing test for save() being called upon $meteorObject initialization

### PR DESCRIPTION
**Pull request by cantoine**
Adding a failing test for issue #800

### CODE REVIEW

**Comment by Urigo** [comment]
@cantoine can you rebase against the current master and see if the test is still failing?

**Comment by Urigo** [comment]
Great!  looks like @DAB0mB has solved the problem

**Comment by cantoine** [comment]
Everything looks good with the test so assuming I wrote it correctly I think we are good. :)

Thanks for all the help @Urigo and @DAB0mB!!

**Comment by Urigo** [comment]
ok, so please check out your app and update issue #800 accordingly 
Thanks for the pull request and the test!

**Pull request merged**
