### PR TITLE
Added text for angular-material login

### PR DESCRIPTION
**Pull request by MilosStanic**
I added text for angular-material login/register/reset password to step 18.

### CODE REVIEW

**Comment by Urigo** [comment]
@MilosStanic nice!
thanks.
Please also add a note about a possible future account-ui in angular and material design package and the relationship with Meteor's accounts-ui

**Comment by MilosStanic** [comment]
@Urigo I'm not sure what exactly you'd like me to write. That we will make the accounts-ui material design version? Please write the note yourself, if it's not too much trouble.

**Comment by Urigo** [comment]
ok cool, I will.

thanks!

**Comment by Urigo** [comment]
@MilosStanic it looks like the recent changes prevent auto merge, can you rebase or merge again?
thanks

**Comment by MilosStanic** [comment]
ok , I created #330  it seems it an auto merge.

**Pull request closed without merging**
