### PR TITLE
New release - Fix for Meteor 1.6.1

### LINKED ISSUE #1855: Incompatible with Meteor 1.6.1-rc.1 due to babel-compiler upgrade
Hi @Urigo and @ardatan 
recently Meteor 1.6.1 was upgraded to use babel-compiler 7.0.0 which breaks angular-meteor compatibility.

An example is to upgrade the examples/MeteorCLI/all-in-one and run it with an updated Meteor.

Running AOT=1 meteor using Meteor 1.6.0.1 works.

Error with 1.6.1:
examples/MeteorCLI/all-in-one

meteor update --release 1.6.1-rc.1
=> Errors while initializing project:         
                                              
While selecting package versions:
error: Conflict: Constraint babel-compiler@6.24.7 is not satisfied by babel-compiler 7.0.0-rc161.1.
Constraints on package "babel-compiler":
* babel-compiler@~7.0.0-rc161.1 <- top level
* babel-compiler@7.0.0-rc161.1 <- ecmascript 0.10.0-rc161.1
* babel-compiler@7.0.0-rc161.1 <- standard-minifier-js 2.3.1-rc161.1
* babel-compiler@7.0.0-rc161.1 <- minifier-js 2.3.1-rc161.1 <- standard-minifier-js 2.3.1-rc161.1
* babel-compiler@6.24.7 <- angular-typescript-compiler 0.2.9 <- angular-compilers 0.2.8_1

Thanks for your help!

### LINKED ISSUE #1881: Build fails for architecture os.linux.x86_64 on windows
### How to reproduce

- On a Windows 10 computer clone angular-meteor-base repository (current Meteor version 1.6)
- Enter dir and do `meteor npm install`
- Try to build the app with `meteor build <outdir> --server-only --architecture os.linux.x86_64` 

Build fails with the error:
```
Loading NgModules!: 0.392ms
{ Error: File to read not found or unreadable: C:/Work/angular-meteor-base/C:/Work/angular-meteor-base/client/imports/app/todo-list/todo-list.scss
    at Object.module.exports.renderSync (C:\Users\username\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16)
    at AngularScssCompiler.compileFile (packages/angular-scss-compiler/index.js:24:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.compiler._host.loadResource.filePath [as loadResource] (packages/angular-typescript-compiler/index.js:279:45)
    at Object.get (C:\Users\username\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler_factory.js:78:306)
....
```
Important part here is the doubling of the directory for the css file **C:/Work/angular-meteor-base/C:/Work/angular-meteor-base**. Seems like the compiler doubles the path.

### Versions

- Windows 10
- Meteor 1.6.1 installed, angular-meteor-base uses version 1.6 (
- angular-compilers@0.2.8_1
- angular-html-compiler@0.2.8
- angular-scss-compiler@0.2.8
- angular-typescript-compiler@0.2.8_1

### Behavior

- Expected: successful build
- Actual: Error above

My own applicaties (with a few other Meteor sub-versions) show the same behavior. I tried to locate the source where the error occurs, but had to face that I don't know exactly which files are used when compiling...

### LINKED ISSUE #1884: angular-compilers does not report module import errors
Using the following set of compiler packages:

> angular-compilers@0.2.8_1
> angular-html-compiler@0.2.9
> angular-scss-compiler@0.2.9
> angular-typescript-compiler@0.2.9

The compiler doesn't report any error or warning for missing modules, it is a huge pain to debug. Could this be a configuration problem in my project, or is this a design choice?

### PR DESCRIPTION
**Pull request by ardatan**
- Fix scss-compiler path issue on Windows closes #1881 and #1852
- Workaround for Zone.js, Meteor Fiber conflict for Universal and All-in-one examples
- Update dependencies for compilers in order to solve Meteor 1.6.1 babel-compiler conflict closes #1855 
- Change rxjs imports to best practive
- Fix logging in some environment closes #1884

### CODE REVIEW

**Comment by klynicol** [comment]
Is this going to take a while to go live, or am I missing something? Still getting babel-compiler conflict when running `meteor add angular-compilers`

**Comment by Urigo** [comment]
yes I haven't published it yet to Atmosphere.
If you want to use it already, run it locally or publish under another name.
I will update as soon as it will be published!

**Comment by Urigo** [comment]
I've released new versions for `meteor-client-bundler` and `meteor-rxjs` already.
for the compiler packages I'm waiting for an answer from @abernix about publishing to Atmosphere and then we're all done.
all the work was being done by the amazing @ardatan !

**Comment by Urigo** [comment]
today we've published the new versions of `angular-compilers` and `meteor-client-bundler`

**Comment by HectorRPL** [comment]
Hello I follow the tutorial: [WhatsApp Clone with Ionic 2 and Meteor CLI](https://angular-meteor.com/tutorials/whatsapp2/meteor/setup) 

I Cant install  `angular2-compilers` but I installed `angular-compilers`

The console sendme this error:
```
node_modules/meteor-typings/1.4/test/test.ts (691, 5): Subsequent variable declarations must have the same type.  Variable 'handle' must be of type 'LiveQueryHandle', but here has type '{ stop: () => void; }'.
node_modules/meteor-typings/1.4/test/test.ts (737, 24): Type '(userId: string) => boolean' has no properties in common with type 'Matcher'.
client/imports/app/app.component.ts (2, 22): Cannot find module './app.html'.
client/imports/app/app.module.ts (4, 11): Argument of type '{ declarations: (typeof MyApp)[]; entryComponents: (typeof MyApp)[]; providers: { provide: typeof...' is not assignable to parameter of type 'NgModule'.
  Types of property 'providers' are incompatible.
    Type '{ provide: typeof ErrorHandler; }[]' is not assignable to type 'Provider[]'.
      Type '{ provide: typeof ErrorHandler; }' is not assignable to type 'Provider'.
        Type '{ provide: typeof ErrorHandler; }' is not assignable to type 'FactoryProvider'.
          Property 'useFactory' is missing in type '{ provide: typeof ErrorHandler; }'.
[client]: TypeScript Files Compilation: 278.553ms
[client]: HTML Files Compilation: 0.907ms
[client]: SCSS Files Compilation: 2.000ms
```

And the crhome console sendme this error:

```
modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:241 Uncaught Error: Cannot find module './app.html'
    at makeMissingError (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:241)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:251)
    at app.component.js (app.js?hash=17c2c85c6dc7929d90d46d3b8b8d74c53bdb940e:11)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at app.module.js (app.js?hash=17c2c85c6dc7929d90d46d3b8b8d74c53bdb940e:37)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at main.js (app.js?hash=17c2c85c6dc7929d90d46d3b8b8d74c53bdb940e:73)
```

my app.component.ts
```
import { Component } from '@angular/core';
import template from "./app.html";

@Component({
    selector: 'my-app',
    template
})
export class MyApp {}
```

friends, Any ideas?

**Comment by atao60** [comment]
Have you tried:

templateUrl: "client/imports/app/app.html";

**Pull request merged**
