### PR TITLE
Update tutorials.socially.angular2.step_04.md

### PR DESCRIPTION
**Pull request by dapids**

### CODE REVIEW

**Comment by Urigo** [comment]
@dapids in the view it looks ok, no?
http://www.angular-meteor.com/tutorials/socially/angular2/adding-removing-objects-and-angular-event-handling#eventhandlers

**Comment by dapids** [comment]
Hi @Urigo,

Yes, it does. Sorry.

If I open the code in the github editor it adds a pipe there, but I don't know why. Next time I'm gonna fork and work locally. ;)

The fix at the line 62 should be fine, instead.

Thanks for the great job, man! :)

**Comment by Urigo** [comment]
@dapids great, so can you edit to pull request to remove the change?

**Comment by dapids** [comment]
@Urigo, it should be ok now.

**Comment by Urigo** [comment]
Thanks @dapids !!

**Pull request merged**
