### PR TITLE
Fix is aot var

### PR DESCRIPTION
**Pull request by iperevozchikov**
This is pull request to fix the bug #1807. Also, was increased package version to 0.2.6 for angular-html-package and angular-scss-package, and their imports in .version files

### CODE REVIEW

**Comment by iperevozchikov** [comment]
Merge last actual version of code into pull request. Fix package version's (angular-html-compiler and angular-scss-compiler) to 0.2.9_1

**Comment by Urigo** [comment]
thank you so much @iperevozchikov !
can you please remove all the version changes and just leave the change itself?

thank you

**Comment by iperevozchikov** [comment]
@Urigo Reverted back package versions to 0.2.9. Stayed only bug fixes.

**Comment by Urigo** [comment]
@iperevozchikov can you please contact me directly through email?
I want to get this merged but want to make sure everything works, including tests

**Comment by ardatan** [comment]
Closed via #1889

**Pull request closed without merging**
