### PR TITLE
Issue $pull update separately from others

### PR DESCRIPTION
**Pull request by MarkPhillips7**
Fix for issue #793

### CODE REVIEW

**Comment by DAB0mB** [comment]
Can you please sync your branch properly instead of commit 2dc49b5?
And also look at [this](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-object.js#L69) line. You can see the callback is not waiting for both update operations to finish, can you please fix that?

**Comment by DAB0mB** [comment]
@MarkPhillips7 can you please also add a test for this scenario?

**Comment by Urigo** [comment]
ok @DAB0mB I'm merging and we will fix it ourselves as I want to get a new version out and I also want @MarkPhillips7 to get the credit

**Comment by MarkPhillips7** [comment]
Sorry about the improper commit and lack of response last couple of days. Still getting used to git and don't have much free time.

**Comment by Urigo** [comment]
@MarkPhillips7 thank you for reporting and sending a fix!

**Pull request merged**
