### PR TITLE
Yago/docs

### PR DESCRIPTION
**Pull request by yagoferrer**
@Urigo 
It took me a while to figure this out, so I think it is a good idea to add: step by step instructions to setup your developer environment to make contributions.

### CODE REVIEW

**Comment by yagoferrer** [comment]
BTW: I seen in other projects a CONTRIBUTING.md file where they put all the contribution notes. I feel that is a good idea to create one and move all this out of the homepage.

**Comment by Urigo** [comment]
That's cool!
But the last part wasn't so clear to me.

Isn't the way to do it is to create a 'packages' folder under your project directory and then just create a shortcut to the angular-meteor folder?
That way you still working with a package called angular-meteor but it's your own local angular-meteor..

What do you think?

**Comment by yagoferrer** [comment]
You can name it `my-package` or  `angular-meteor` it works either way. I guess I tried to explain by example that you can call it whatever you want. The benefit of having a central place for your local packages is that you can add them to several projects without having to copy the entire folder. I haven't try the option to create a `packages` folder and just dump the project. Sounds easier to me!

**Comment by Urigo** [comment]
OK, I'm merging and changing it a bit

Thanks!

**Comment by yagoferrer** [comment]
ok great! thank you I'm trying this out.

**Comment by Urigo** [comment]
Cool, then let me know if my explanation is OK

**Comment by yagoferrer** [comment]
Ok, let me simplify this.

**Pull request merged**
