### PR TITLE
documentation structure changes

### PR DESCRIPTION
**Pull request by oshai**

### CODE REVIEW

**Comment by Urigo** [comment]
@oshai I've rebuild the whole site...
so can you rebase your changes on top of the new site?
thanks

**Comment by oshai** [comment]
I didn't have time to do the merge yet. I guess it is not relevant anymore?

**Comment by Urigo** [comment]
might be, just on the new structure

**Comment by oshai** [comment]
I am sorry, but it seems too difficult (for me) to merge it at this time.

**Pull request closed without merging**
