### PR TITLE
Updates for the all-in-one compiler

### PR DESCRIPTION
**Pull request by barbatus**
Changes:
1. Compiles now take a custom function to add compilation result that is supposed to be used in other compilers (like future all-in-one angular compiler)
2. Use lodash instead of underscore due to its better modular structure which helps to reduce package size
3. Import temporary amgular2-meteor-polyfills for main/browser, remove browser from package.json
Fix some lint issues/compiler warnings

### CODE REVIEW

**Comment by dotansimha** [comment]
Something goes wrong with the SCSS compiler. 
When using those compilers with the Ionic2-MeteorCLI tutorial, the SCSS files does not compile and bundled into the client js file, and the errors is:
```
modules-runtime.js?hash=637cb12…:119Uncaught Error: Cannot find module './chats.component.scss'
    at require (modules-runtime.js?hash=637cb12…:119)
    at meteorInstall.client.imports.pages.chats.chats.component.js (chats.component.ts:8)
    at fileEvaluate (modules-runtime.js?hash=637cb12…:191)
    at require (modules-runtime.js?hash=637cb12…:116)
    at meteorInstall.client.imports.pages.tabs-container.tabs-container.component.js (tabs-container.component.ts:2)
    at fileEvaluate (modules-runtime.js?hash=637cb12…:191)
    at require (modules-runtime.js?hash=637cb12…:116)
    at meteorInstall.client.imports.app.app.component.js (app.component.ts:6)
    at fileEvaluate (modules-runtime.js?hash=637cb12…:191)
    at require (modules-runtime.js?hash=637cb12…:116)
require @ modules-runtime.js?hash=637cb12…:119
meteorInstall.client.imports.pages.chats.chats.component.js @ chats.component.ts:8
fileEvaluate @ modules-runtime.js?hash=637cb12…:191
require @ modules-runtime.js?hash=637cb12…:116
meteorInstall.client.imports.pages.tabs-container.tabs-container.component.js @ tabs-container.component.ts:2
fileEvaluate @ modules-runtime.js?hash=637cb12…:191
require @ modules-runtime.js?hash=637cb12…:116
meteorInstall.client.imports.app.app.component.js @ app.component.ts:6
fileEvaluate @ modules-runtime.js?hash=637cb12…:191
require @ modules-runtime.js?hash=637cb12…:116
meteorInstall.client.imports.app.app.module.js @ app.module.ts:2
fileEvaluate @ modules-runtime.js?hash=637cb12…:191
require @ modules-runtime.js?hash=637cb12…:116
meteorInstall.client.main.js @ main.ts:7
fileEvaluate @ modules-runtime.js?hash=637cb12…:191
require @ modules-runtime.js?hash=637cb12…:116
(anonymous) @ users.collection.ts:5
```

**Comment by dotansimha** [comment]
Also, without the CSS content bundled into the Component, we won't be able to do real lazy loading - because we want each Component or NgModule as a single file, with it's assets inside.

**Comment by barbatus** [comment]
I guess you trying the version from this PR? This version is missing the part that adds JS modules; it's expected to happen now here https://github.com/barbatus/angular2-compiler/blob/master/asset-compiler.js#L52.

**Comment by barbatus** [comment]
So `css-compilers` v0.3.6 is the current old version now, v0.4.1 - for the upcoming compiler.

**Comment by dotansimha** [comment]
@barbatus 
I updated the packages locally, now using the latest from the PR (with `css-compilers@0.4.1`). 
Still unable to load SCSS files as modules: `Uncaught Error: Cannot find module './login.component.scss'`. HTML files works, but stylesheet files does not added to the bundle as js modules :(

**Comment by barbatus** [comment]
@dotansimha css-compilers@0.4.1 will work only with this package https://github.com/barbatus/angular2-compiler. css-compilers @v0.3.6 works with the currently published angular2-compilers.

**Comment by dotansimha** [comment]
So I don't understand why this PR is here, can you please explain? because I think we can't merge it at the moment - it breaking the current API... the barbatus/angular2-compiler package should be merge into this repo? @barbatus

**Comment by barbatus** [comment]
yes, barbatus/angular2-compiler will likely be added to this repo. I wanted to tell that it's breaking but only for the  css-compilers. From the other side, css-compilers @v0.3.6 is stable (this particular version we'll continue use it in angular2-compilers), which means if we merge this PR now it should not cause issues while work on the new compiler is still in progress. Probably now I'd already keep it as is (not merged) if it causes so many questions from you.

**Comment by dotansimha** [comment]
I see. the only issue in my side is the fact that it's breaking all of the tutorial and boilerplate we have, and we need to change all of the tutorial's instructions for the new usage... Is that a problem to release 0.4.1 css package with the js module? (so it won't break anything)

**Comment by barbatus** [comment]
@dotansimha it's not a problem. But 0.4.1v has minor number up which means it's potentially breaking (that's why I raised it btw). We just need to tell people that's breaking and recommend to use 0.3.6 for now. I'll talk to Uri; we can potentially release some initial compiler version on the next week (it anyways should be better then the current even w/o AoT).

**Comment by Urigo** [comment]
Also tracking here - https://github.com/barbatus/angular2-compiler/issues/2

**Comment by Urigo** [comment]
Suppressed by @ardatan PR [here](https://github.com/Urigo/angular-meteor/pull/1654)
Thank you @barbatus for the great help!

**Pull request closed without merging**
