### PR TITLE
fix(angular-templates): importing one file in different ways

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by Ben305** [comment]
@kamilkisiela Thanks, tried it and it works again 👍

**Comment by kamilkisiela** [comment]
@Ben305 Great to hear that! :ok_hand:

**Comment by Ben305** [comment]
@kamilkisiela I'm seeing some Template does not exist errors, these don't show up with 1.0.3. Will check that tomorrow and post more infos then.

**Comment by kamilkisiela** [comment]
@Ben305 It would be awesome to have a reproduction pattern or something. Please open a new issue for it :) You can @mention me there!

**Comment by fpaboim** [comment]
@kamilkisiela I have an app that I built following the old directives styles from the tutorial, e.g.:
```
angular.module('myapp').directive('myapp', function () {
  return {
    restrict: 'E',
    templateUrl: 'client/myapp.html',
    controllerAs: 'myapp',
    controller: function ($scope, $state, $reactive, $rootScope, $timeout, ....
```
I'm still getting the the error:
```
Error: [angular-meteor][err][404] client/myapp.html - HTML template does not exists! You can disable this error by following this guide http://www.angular-meteor.com/api/1.3.11/templates
    at Object.$delegate.get (angular-templates.js:65)
    at handleRequestFn (angular_angular.js:18761)
    at compileTemplateUrl (angular_angular.js:9302)
    at applyDirectivesToNode (angular_angular.js:8858)
    at compileNodes (angular_angular.js:8271)
    at compileNodes (angular_angular.js:8283)
    at compileNodes (angular_angular.js:8283)
    at compileNodes (angular_angular.js:8283)
    at compile (angular_angular.js:8170)
    at angular_angular.js:1730
```
which used to work before without errors, do I have to change all my templates to the new lazy loading style for my app to work with the latest release? Don't know if it's related to this fix but the symptoms seem to be the same as the people in the thread. I'm using 1.4 with angular templates 1.0.8_1. Thx!

**Comment by pacozaa** [comment]
@fpaboim I have to same error. Now I'm trying to change angular templates version.

**Comment by TWKDreamState** [comment]
@fpaboim Same here too. I haven't been able to work on my app for about a month due to time constraints, did the updates to Meteor 1.4, Angular-Meteor, etc and I'm getting this error with Angular Templates version 1.0.8_1. Are we able to still use the templateUrl as previously?

`angular_angular.js:13439 Error: [angular-meteor][err][404] client/home/home.view.html - HTML template does not exists! You can disable this error by following this guide http://www.angular-meteor.com/api/1.3.11/templates
    at Object.$delegate.get (http://localhost:3000/packages/angular-templates.js?hash=66eabcc1ed0f45b1be8d8daf598a7d2041e79520:65:23)
    at handleRequestFn (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:18761:45)
    at compileTemplateUrl (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:9302:7)
    at applyDirectivesToNode (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:8858:24)
    at compileNodes (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:8271:15)
    at compile (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:8170:15)
    at http://localhost:3000/packages/modules.js?hash=b14be2a0ee5da3c54d3339168b0e0ab90be88ed6:27225:20
    at invokeLinkFn (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:9638:9)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:9037:11)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e:8348:13) <div ui-view="" class="ng-scope" data-ng-animate="1">`

**Comment by kamilkisiela** [comment]
@TWKDreamState It should be with by https://github.com/Urigo/angular-meteor/pull/1412

**Pull request merged**
