### PR TITLE
ng2 tutorial step15 edits

### PR DESCRIPTION
**Pull request by ShMcK**
Rephrasing for clarity, typos, etc. No code edits.

### CODE REVIEW

**Comment by Urigo** [comment]
@ShMcK for some reason this change breaks chapter 15..  can you look into that ?

thanks

**Comment by ShMcK** [comment]
@Urigo. I looked into it, but it seems to be working. [chapter-15](http://www.angular-meteor.com/tutorials/socially/angular2/conditional-template-directives-with-angularjs).

**Comment by Urigo** [comment]
it works on the website because I haven't deployed it yet because it didn't ran on my local machine

**Comment by ShMcK** [comment]
The "<11" mention of the version number was likely the culprit, probably interpreted as an HTML tag with the following line starting with ">"

**Pull request merged**
