### PR TITLE
Update tutorials.socially.angular1.step_18.md

### PR DESCRIPTION
**Pull request by ThomsC**
In this package there is a lack of icons as many more were added to the list. So I created a package that add these new icons. 
I don't know where to add the code in the template : 

$mdIconProvider
            .iconSet("action", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-action.svg")
            .iconSet("alerte", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-alert.svg")
            .iconSet("av", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-av.svg")
            .iconSet("communication", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-communication.svg")
            .iconSet("content", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-content.svg")
            .iconSet("device", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-device.svg")
            .iconSet("editor", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-editor.svg")
            .iconSet("file", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-file.svg")
            .iconSet("hardware", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-hardware.svg")
            .iconSet("image", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-image.svg")
            .iconSet("maps", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-maps.svg")
            .iconSet("navigation", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-navigation.svg")
            .iconSet("notification", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-notification.svg")
            .iconSet("places", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-places.svg")
            .iconSet("social", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-social.svg")
            .iconSet("toggle", "/packages/thoms_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-toggle.svg");

### CODE REVIEW

**Comment by Urigo** [comment]
@mxab

**Comment by mxab** [comment]
hi i released a 2.1.1 icons package.

What do you mean by  "I don't know where to add the code in the template :"

**Comment by ThomsC** [comment]
Sorry I'm new to gitHub. 

I meant I didn't know where to add the code to modify the tutorial because all I saw was this line :
{{> DiffBox tutorialName="meteor-angular1-socially" step="18.3"}}

Great for your released!

**Comment by Urigo** [comment]
@ThomsC yes it's a little bit hard to change the code.
We use this tool to generate to source code from the repository - http://info.meteor.com/blog/step-by-step-tutorials-with-git

If you don't want to learn that, you can open an issue with what you want to change in the source and I will change it

**Pull request closed without merging**
