### PR TITLE
Create a raw object getter.

### LINKED ISSUE #247: Using an AngularMeteorObject as argument for $meteor.call.
I get an object from the database with `$meteor.object(Coll, id, false)` and set it to a $scope variable. I then try to save the object when a save button is clicked. I use a method call for saving, because I need to touch some users while saving. `$meteor.call('updateObj', $scope.obj.id, $scope.obj)`.

At this point the code fails miserably because the AngularMeteorObject has some circular references and makes EJSON fail. `Uncaught RangeError: Maximum call stack size exceeded`

Is there a way to use the AngularMeteorObject as an argument to a method call, other than hand-picking the properties from the object to a new plain object?

I can provide sample code later if needed.

### PR DESCRIPTION
**Pull request by JNissi**
* Added a method to AngularMeteorObject that returns a copy of the object without any of the internalprops.
* Fixes #247

### CODE REVIEW

**Comment by Urigo** [comment]
@JNissi 
1. Do you want to reconsider the name?
2. Can you add documentation to the API docs as well?

**Comment by JNissi** [comment]
@Urigo 
1. Changed the name. ^^
2. Does the documentation of AngularMeteorObject really go to http://angularjs.meteor.com/api/AngularMeteorCollection ? I've been thinking the docs seem a bit fudged up on this front.

**Comment by Urigo** [comment]
Great, merging.

About the docs, do you mean this: http://angularjs.meteor.com/api/meteorObject

**Comment by Urigo** [comment]
ohh, about the docs, @srtucker22 's pull request fixes that - https://github.com/Urigo/angular-meteor/pull/228
I'll wait for him to update his pull request so I can merge it and then you can open another one for your docs.

**Comment by JNissi** [comment]
Ookay, I'll follow that one and update the docs when possible.

**Comment by srtucker22** [comment]
@Urigo should be good to go now

**Comment by Urigo** [comment]
Great!
@JNissi you can go for it now

**Comment by Urigo** [comment]
@JNissi  what's your Twitter handle (for the new version announcement)?

**Comment by JNissi** [comment]
JiiNissi

**Pull request merged**
