### PR TITLE
changed prefix in comment

### PR DESCRIPTION
**Pull request by simonv3**
It should be a reference to the user's meteor developer account name, no?

### CODE REVIEW

**Comment by Urigo** [comment]
@simonv3 I think that depends if it's a local package or a published one but I'm not sure..
Can you make sure and post it here?

**Comment by simonv3** [comment]
@Urigo Hmm, you're right, they are different, but if it's a local package it doesn't need the `my-app` bit at all, then you just do `my-package`. I guess what's different is that the package name of a published package just includes the developer name - ie `simonv3:simon-package` would be the full name of the package, and the `:` would just get replaced with a `_`.

**Comment by Urigo** [comment]
so maybe can you edit it to be a bit more understandable, like saying package name and give an example?

**Comment by Urigo** [comment]
thanks!

**Pull request merged**
