### PR TITLE
docs(tutorialAngular2.step_06.html): fix typos

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by ShMcK** [comment]
Everything here looks good, with one exception. 

As of [Angular 2 alpha.35](https://github.com/angular/angular/blob/master/CHANGELOG.md), injectables and common directives have become uppercased. I believe `formDirectives` is now `FORM_DIRECTIVES`. These changes should also effect the `routerDirectives` & `routerInjectables` in the next release.

@IgorMinar, could you try running the lastest version of `shmck:angular2` to check on this? 

Running `meteor update` generally works (as can be verified in `.meteor/versions`). Though sometimes I've found it necessary to erase everything in `.meteor/versions` and re-run `meteor`.

**Comment by IgorMinar** [comment]
Yes. As of 35 both should be all caps.

**Comment by Urigo** [comment]
@IgorMinar can you please update your PR so that FORM_DIRECTIVES would stay capitalize?
I can also update it myself if you prefer 
thank you so much for all your help, looking forward for more feedback when the new package will be out!

**Comment by IgorMinar** [comment]
done

**Comment by Urigo** [comment]
Thanks!

**Pull request merged**
