### PR TITLE
docs(general) Clean up tutorial files

### PR DESCRIPTION
**Pull request by birkskyum**
Remove duplicate code for tutorial sidebar/routes.
Move "tutorials" package to "/private" and decouple it, to simplify the tutorials.
Some naming of tutorial files/patches fixed.

### CODE REVIEW

**Comment by Urigo** [comment]
@birkskyum thank you so much!
 can you please rebase against the recent changes?

**Comment by birkskyum** [comment]
@Urigo it is rebased now.

**Comment by Urigo** [comment]
@birkskyum what is all the renaming files at the beginning?
also why did you remove the links from the navbar?

**Comment by birkskyum** [comment]
The renaming in the beginning are files being moved into /client/content.

The folder structure of the client was:
client
   /content  
      /angular-server
      /api
      /patches
      /tutorials
   /home

I just gave each page, from the navigation, a folder inside content, so it became:

client
   /content  
      /about-us
      /angular-2
      /angular-server
      /api-reference
      /home
      /manifesto
      /tutorials

Patches are now under their respective tutorials.

About the navigation links. It looks like there begins to be several tutorials, and it therefore might make sense to remove the dropdown completely and make a /tutorials page. It could just be an image and a description, but I think it could make a good impression. Another thing is that the navigation links i removed all are from the Socially tutorial, but they are maintained separately, and they therefore easily become out of sync.

**Comment by Urigo** [comment]
there is benefits in seeing all the chapters from the start.
It shows developers how comprehensive the tutorial is

**Comment by birkskyum** [comment]
Your right, and it also looks better. I have added them again.

**Comment by Urigo** [comment]
of course it will be great if we will have a code that generates the links in the navbar

**Comment by Urigo** [comment]
but it's not a must

**Comment by birkskyum** [comment]
It's updating automatically now.

**Comment by Urigo** [comment]
Awesome!

**Pull request merged**
