### PR TITLE
$scope subscribe, collection, and object methods prefixed with $meteor

### PR DESCRIPTION
**Pull request by auterium**
As discussed in #304

### CODE REVIEW

**Comment by auterium** [comment]
@Urigo I know you're packed with work, but any idea if this is going through?

**Comment by Urigo** [comment]
Hi sorry!
I'm in SF meeting with Meteor and Angular, a lot of really good things are coming.
Tonight I will go through your pull request!

**Comment by auterium** [comment]
That's cool. Thanks for the reply. I wanted to know as I'm already using this things for projects, and I would like to use it directly from the published package and not from a local one.

**Comment by Urigo** [comment]
That great, it make me more relaxed on merging it
Good job!

**Comment by auterium** [comment]
Thanks! Are there any upcoming meetings you're going to in the US? When I heard about ng-vegas it was too late for me to buy a ticket or anything, but it would be nice to go to one and meet.

**Comment by Urigo** [comment]
Unfortunately I'm flying out this Saturday..
But I'll probably be back soon

**Pull request merged**
