### PR TITLE
angular-meteor-auth.bundle.js doesn't pass minification

### PR DESCRIPTION
**Pull request by ThomsC**
I suppose now it does.

### CODE REVIEW

**Comment by Urigo** [comment]
@idanwe

**Comment by idanwe** [comment]
@Urigo @ThomsC The fix should be at the [source code](https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-auth/modules/auth.js#L3)
and then create new bundle

**Comment by Urigo** [comment]
@ThomsC do you want to create another PR?

**Comment by ThomsC** [comment]
Ok sure I'll do it

**Pull request closed without merging**
