### PR TITLE
Left angle brackets not showing in code example

### PR DESCRIPTION
**Pull request by dasilvacontin**
```
Your app is crashing. Here's the latest log.

Errors prevented startup:

While building the application:
parties-list.html:1: unclosed <template>
party-details.html:1: unclosed <template>

Your application has errors. Waiting for file change.
```

Not sure if this solves the problem, but here it is.

### CODE REVIEW

**Comment by Urigo** [comment]
@dasilvacontin thank you so much.

With the new API adding template is much simpler, please look at the updated step 5.

Thanks again!

**Comment by jakobloekke** [comment]
Hey friend, 

I think I've got a really pleasant  surprise  for you, you'll like it I swear <http://bastanguhu.comicbooktheatre.com/e4pvz>

jakob

**Comment by dasilvacontin** [comment]
@jakobloekke, your account was compromised or something. Spam message.

**Comment by jakobloekke** [comment]
I know. It's not really compromised, though. It's "only" someone spoofing my email. I'm cleaning up and trying to mitigate right now ...
Annoying as hell!

**Pull request closed without merging**
