### PR TITLE
targeted updating feature for objects

### PR DESCRIPTION
**Pull request by srtucker22**
an idea for targeted updating for meteor.objects -- this can be handy if i don't want the whole object to get overridden. for example, if i use collection2 autoValues, i might not want to trigger those every time i update the object -- or if i use collectionhooks after an update, etc.

### CODE REVIEW

**Comment by Urigo** [comment]
@srtucker22 can you link to an example?

**Comment by Urigo** [comment]
@srtucker22 I want to merge it but want to see a simple scenario first and also update to docs so people will know how to use it.
And thank you so much!

**Comment by srtucker22** [comment]
No problem. Here's a short example:

        Parties = new Mongo.Collection("parties");

        var Schema = {};

        Schema.Party = new SimpleSchema({
          name: {
            type: String,
            label: "name",
          },
          description: {
            type: String,
            label: "description"
          },
          nameModified: {
            type: Date,
            autoValue: function() {
              if (this.field("name").isSet) {
                return new Date();
              }
            },
            denyInsert: true,
            optional: true
          }
        });

        Parties.attachSchema(Schema.Party);

        if (Meteor.isClient) {

          angular.module('app',['angular-meteor']);

          angular.module("app").controller("PartiesListCtrl", ['$scope', '$meteor',
            function($scope, $meteor){
              
              // will only edit the description
              $scope.editDescriptionOnly = function(party){
                var p = $meteor.object(Parties, party._id, false);
                p.save({description: party.description});
              };

              // will edit the whole object and change nameModified
              $scope.fullUpdate = function(party){
                var p = $meteor.object(Parties, party._id, false);
                p.description = party.description;
                p.save();
              };

            }]);
        }

If you call editDescriptionOnly, you won't <code>$set</code> every field when you update. In this case, if you just call <code>party.save()</code> you would trigger <code>autoValue</code> from collection2 that is supposed to only track when the name is modified.

An alternative to my approach might be to:
1. track all changes on a <code>$meteor.object</code>
2. <code>$set</code> the diff between the db instance and the current object. this would require an extra call to the server <code>findOne(obj._id)</code> and finding a deep diff between the two objects 

Both of those options seem overly computationally expensive to me for most cases.

If you like the change, I can update the docs too :)

**Comment by Urigo** [comment]
Yes I like it :)

here is a link to the docs - https://github.com/Urigo/angular-meteor/blob/master/.docs/angular-meteor/client/views/api/api.meteorObject.html

**Comment by Urigo** [comment]
Waiting for your docs update to merge.
Great job and thank you so much!

**Comment by srtucker22** [comment]
Happy to edit my commit as necessary. I noticed the link to AngularMeteorObject on http://angularjs.meteor.com/api/meteorObject led to AngularMeteorCollection, so I copied the format and applied to a new AngularMeteorObject page (and added it to the nav).

**Comment by Urigo** [comment]
@fredrikekelund can you have a look?  you've done something similar in our collection

**Comment by Urigo** [comment]
@srtucker22 great job, looking at it now

**Comment by Urigo** [comment]
@srtucker22 can you merge with the latest changes so I can merge?

**Comment by Urigo** [comment]
@srtucker22 what's your Twitter handle (for the new version announcement)?

**Comment by srtucker22** [comment]
@simonrtucker <https://twitter.com/simonrtucker> !

Simon Tucker

Cell: (973) 768-8791
LinkedIn <http://www.linkedin.com/in/simonrtucker> | Twitter
<https://twitter.com/simonrtucker>

**Pull request merged**
