### PR TITLE
Makes Home and About pages mobile-friendly

### PR DESCRIPTION
**Pull request by barbatus**
Makes Home and About pages mobile-friendly.
Re-factor/clean-up of existing styles.
Deployed http://ng-meteor.meteor.com.
Tested with different size on Chrome mobile mode,
also tested on iphone 5s

### CODE REVIEW

**Comment by Urigo** [comment]
That great, just one small note, I like it better when the menu on the left was separated from the header (small white space between them).
Is it ok to return it @barbatus ?

**Comment by barbatus** [comment]
@Urigo I just compared with the prev version: it looks the same to me.
I guess a screenshot would be superb to point that out.

**Comment by barbatus** [comment]
@Urigo BTW, the guy who has done this merge https://github.com/Urigo/angular-meteor/commit/88b50bf0ee092ecd93ca5f1f6d6be664ad457aeb wasn't cautious enough to include 4th part of my prev changes from here https://github.com/Urigo/angular-meteor/commit/42c3b8d670e44c37fc50ab706ea27d798f514c3b, including important ones like
avoiding double copying https://github.com/Urigo/angular-meteor/commit/42c3b8d670e44c37fc50ab706ea27d798f514c3b#diff-32cf712277b42c3ac88358aa2911a7f4L292

Also this line is suspicious https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L58, it seems should be ````keys = _.pluck(this, '_id'); ````

Looks like one more PR is needed.

**Comment by Urigo** [comment]
@DAB0mB

**Comment by Urigo** [comment]
@barbatus 
screen shot 2015-08-05 at 12 42 06 pm
screen shot 2015-08-05 at 12 42 09 pm

**Comment by barbatus** [comment]
@Urigo please see my new commit

**Comment by Urigo** [comment]
@barbatus can you please deploy the updated version to http://ng-meteor.meteor.com  ?

**Comment by barbatus** [comment]
@Urigo Commit description says it's deployed here http://ng-meteor-2.meteor.com

**Comment by Urigo** [comment]
ok got it.
The only note I have is that the links on angular-server API should look like the links on the API

**Comment by barbatus** [comment]
@Urigo Fixed

**Comment by Urigo** [comment]
Awesome!

**Pull request merged**
