### PR TITLE
Update tutorial.step_18.html

### PR DESCRIPTION
**Pull request by tomtom42**
I think the ng-app tag is missing in this example.

### CODE REVIEW

**Comment by idanwe** [comment]
It isn't because the app is bootstrap `angular.bootstrap` take a look at: https://github.com/Urigo/angular-meteor/blob/master/.docs/angular-meteor/client/lib/app.js#L15

**Comment by tomtom42** [comment]
Ok, I tried to work through the tutorial and at that step it stopped working when pasting that code.

When I inserted ng-app... it started working  again.

**Comment by Urigo** [comment]
@tomtom42 can you please open it as an issue and provide your code in a repo so I can reproduce?
thanks

**Comment by tomtom42** [comment]
Hello Uri,

I guess this won't be necesarry.

I went through the tutorial, which is a great helper for me to get into
this up to step 13.

Afterwards I went the short way to step 18 as that interested me very much.

When I pasted the new code from the first step in step 18, I only got a
blank page.
I re-inserted that ng-app tag, as that was the most obvious difference for
me, the project started working again.

I just checked out step18 from your repository and it works here, so there
must have been something in my version.

So excuse me for being too fast hitting the improve docs button.

I appreciate your great work and it helped me a lot to take the first steps
into an app I just work on to "warm up" and get productive.

So keep up the work and don't waste your time looking into this issue.

All the best,

Tom


Uri Goldshtein <notifications@github.com> schrieb am So., 26. Juli 2015 um
14:18 Uhr:

**Comment by Urigo** [comment]
Thanks for your kind words @tomtom42 !
Good luck!

**Pull request closed without merging**
