### PR TITLE
auth.js doesn't pass minification

### PR DESCRIPTION
**Pull request by ThomsC**
I suppose now it does.

### CODE REVIEW

**Comment by ThomsC** [comment]
Do you know when this meteor package will update? Because I kind of need it in production side...

Thanks

**Comment by Urigo** [comment]
ok then tomorrow I'll release a new version with this fix and with the new babel dependency

**Comment by Urigo** [comment]
Released

**Comment by ThomsC** [comment]
@Urigo Thanks for the release (and happy new year !)

Is angular 1.3.3 include angular-meteor-auth now because I can't see an update for this package.

And after the update my app doesn't start anymore. I got this error which doesn't mean a lot to me.

```
W20160102-17:45:27.078(1)? (STDERR) /Users/Thoms/.meteor/packages/meteor-tool/.1.1.10.r3ykmi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160102-17:45:27.078(1)? (STDERR) 						throw(ex);
W20160102-17:45:27.078(1)? (STDERR) 						      ^
W20160102-17:45:27.078(1)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation in field maxSize
=> Exited with code: 8
```

**Comment by Urigo** [comment]
I've updated angular-meteor-auth on 1.3.4.
Please check that version and let me know

**Comment by ThomsC** [comment]
I've tested angular 1.3.4 on an new project and everything seems to work find.

but on my project I got this error : 

```
W20160103-10:57:39.024(1)? (STDERR) `Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`
W20160103-10:57:39.138(1)? (STDERR) 
W20160103-10:57:39.138(1)? (STDERR) /Users/Thoms/.meteor/packages/meteor-tool/.1.1.10.r3ykmi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160103-10:57:39.138(1)? (STDERR) 						throw(ex);
W20160103-10:57:39.138(1)? (STDERR) 						      ^
W20160103-10:57:39.153(1)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation in field maxSize
```

I supposed this error should come from a package? Do I have any way to have a more precise message for this error?

Great for  `angular-meteor-auth` everything is ok !

**Comment by Urigo** [comment]
maybe it's related to this:
https://github.com/Urigo/angular-meteor/issues/988

**Comment by ThomsC** [comment]
solved with `angular-babel@1.0.9`

**Pull request merged**
