### PR TITLE
Tests for the Angular Services

### PR DESCRIPTION
**Pull request by yagoferrer**
Hey Uri, 
I started working on writing the tests for the Angular Services. You can run them doing this:

```bash
npm install
npm test
```

more tests coming soon.

### CODE REVIEW

**Comment by Urigo** [comment]
Amazing, will test that later today.

Thank you so much!

**Comment by Urigo** [comment]
# Best 
# Pull 
# Request 
# Ever
# !!

**Comment by yagoferrer** [comment]
Thanks! Please add me as a collaborator and I'll work on a branch adding more tests.

**Comment by Urigo** [comment]
Done.
Can't wait

**Comment by yagoferrer** [comment]
Awesome thank you! Please add "Travis CI" as webhook so that all tests will run for each commit.

**Comment by Urigo** [comment]
https://github.com/Urigo/angular-meteor/issues/118

**Pull request merged**
