### PR TITLE
Added currentUserPromise to the $rootScope

### PR DESCRIPTION
**Pull request by revov**
issue #181
@Urigo, this is my first pull request, so please review my changes. Now it should be sufficient to just set in your route config:
```javascript
$stateProvider
    .state('home', {
        url: '/',
        templateUrl: 'client/views/home.tpl',
        controller: 'HomeController'
        resolve: {
            currentUser: $rootScope.currentUserPromise
        }
    });
```
Or if you don't want to hide the reactive $rootScope.currentUser in yout controller's scope, just assign it to another property:
```javascript
$stateProvider
    .state('home', {
        url: '/',
        templateUrl: 'client/views/home.tpl',
        controller: 'HomeController'
        resolve: {
            currentUserNonReactive: $rootScope.currentUserPromise
        }
    });
```
It is also a good idea to maybe add the currentUserPromise to the unit tests.

### CODE REVIEW

**Comment by Urigo** [comment]
@revov I think in the examples you used exactly the same variable in both cases, is that right?

**Comment by Urigo** [comment]
@revov can you also add a bit of documentation to the API reference?

**Comment by Urigo** [comment]
@revov any news?

**Comment by revov** [comment]
Sorry @Urigo but I really don't have the spare time until the weekend. If you could help me with the documentation or at least guide me into where should I put it that would be really helpful.

I like your package, I use it in two of my personal projects and have a lot of improvements to offer, so I plan on more serious contributions in the future.

**Comment by revov** [comment]
@Urigo, Updated the API reference. Feel free to improve it.

**Comment by Urigo** [comment]
Great @revov !!  
Thank you so much!

**Pull request merged**
