### PR TITLE
Update docs to use requireValidUser()

### PR DESCRIPTION
**Pull request by auterium**
As per @Urigo request

### CODE REVIEW

**Comment by Urigo** [comment]
@auterium thanks!
maybe you should also document that there is no need to actually send the 'user' parameter?
also, maybe just remove it for the example? will it still work?

**Comment by auterium** [comment]
@Urigo I can't think of a scenario where to use it without the user argument

**Comment by Urigo** [comment]
@auterium but the user argument is supplied inside anyway no?

**Comment by auterium** [comment]
Ohh you mean there's no need to do the
```javascript
return $meteor.requireValidUser()
```
stuff?

The callback that the function receives will always be executed pasing the user as the only argument

**Comment by Urigo** [comment]
yes.. so like add a comment about it or something so people will understand where is it coming from

**Pull request merged**
