### PR TITLE
Include file path in the cache key of NgCachingHtmlCompiler

### PR DESCRIPTION
**Pull request by sebakerckhof**
Fixes https://github.com/Urigo/angular-meteor/issues/888

Note that I can't seem to clone or commit without deleting these files in `.npm_old`, git gives me all kinds of erros.

### CODE REVIEW

**Comment by sebakerckhof** [comment]
@Urigo any time to look into this?

**Comment by EvilJohnny** [comment]
I am also looking fordward to this to be fixed! :smiley:

**Comment by Urigo** [comment]
@sebakerckhof thank you for that and sorry for the late response.
I'm merging and releasing a new version

**Comment by Urigo** [comment]
Released in `1.2.3`

**Pull request merged**
